### ISSUE TITLE
Is it yet another nuclei like scanner?

### ISSUE THREAD

**Issue by jakre1234** [knassar702/scant3r#38]
Hello Devs,
I am liking your project from the outer view cause I haven't tied it yet but wanted to know something regarding this tool. What's the purpose of this tool? I can see we need to pass in urls for scanning, is it like fuzzing payloads or we need to put in subdomains? Also, do we need to crawl and spider and collect the endpoints to pass it on to this tool. I am not able to understand the wokflow of this, it would be nice if you can make the README.md more descriptive.

Thanks.

**Comment by knassar702** [comment]
hello @jakre1234 , thanks for this issue , scant3r is a Modules-based security tool like Nuclei scanner but with python modules our goal is make writing automation scripts easy for save user time with providing many functions for help the user  ,also you can use [simple YAMl file](https://github.com/knassar702/scant3r/tree/master/modules/python/cve/list/templates) for scanning (`We will make it better in the new version`) , and you can add [non-python scripts] (https://github.com/knassar702/scant3r/tree/master/modules/scripts) and shell commands with scant3r options

```yaml
exec: echo {url} | xargs curl --timeout {timeout} 


remove: # remove the Banner of the tool
  word: curl.*.
  regex: false
# matching with success results
match: hackerman

```

this a quick description, in this week i'll write a Clear Documentations because I'm a bit busy right now

If you have any questions, feel free to ask :D 
best regards 
@knassar702
